'use strict';
// คลังสถานที่ของเกมสายลับ แยกเป็นชุด — เพิ่ม/แก้ได้เลย
// แต่ละสถานที่มีบทบาท (อาชีพ) ให้ผู้เล่นสวมบท ถ้าผู้เล่นมากกว่าบทบาท ระบบจะวนใช้ซ้ำ
// en / rolesEn = ชื่อภาษาอังกฤษ (rolesEn เรียงตรงกับ roles)

const LOCATION_PACKS = {
  classic: {
    name: 'สถานที่ทั่วไป', en: 'Classic places', icon: '🌍', desc: 'สถานที่คลาสสิกจากทั่วโลก', descEn: 'Classic places from around the world',
    list: [
      { name: 'เครื่องบิน', en: 'Airplane', icon: '✈️', roles: ['กัปตัน', 'แอร์โฮสเตส', 'ผู้โดยสารชั้นธุรกิจ', 'ผู้โดยสารชั้นประหยัด', 'ช่างเครื่อง', 'เด็กร้องไห้', 'สจ๊วต'],
        rolesEn: ['Captain', 'Flight attendant', 'Business-class passenger', 'Economy passenger', 'Mechanic', 'Crying child', 'Steward'] },
      { name: 'ธนาคาร', en: 'Bank', icon: '🏦', roles: ['ผู้จัดการ', 'พนักงานเคาน์เตอร์', 'ยามรักษาความปลอดภัย', 'ลูกค้ามาฝากเงิน', 'โจรปล้นธนาคาร', 'ที่ปรึกษาการลงทุน', 'คนขับรถขนเงิน'],
        rolesEn: ['Manager', 'Teller', 'Security guard', 'Customer making a deposit', 'Bank robber', 'Investment advisor', 'Armored-truck driver'] },
      { name: 'ชายหาด', en: 'Beach', icon: '🏖️', roles: ['ไลฟ์การ์ด', 'คนขายมะพร้าว', 'นักเล่นเซิร์ฟ', 'นักท่องเที่ยว', 'ช่างภาพ', 'เด็กก่อปราสาททราย', 'หมอนวดริมหาด'],
        rolesEn: ['Lifeguard', 'Coconut seller', 'Surfer', 'Tourist', 'Photographer', 'Kid building sandcastles', 'Beach masseuse'] },
      { name: 'โรงหนัง', en: 'Movie theater', icon: '🎬', roles: ['คนขายตั๋ว', 'คนขายป๊อปคอร์น', 'คู่รักมาเดต', 'นักวิจารณ์หนัง', 'พนักงานเช็ดโรง', 'คนแอบถ่ายหนัง', 'เด็กมากับพ่อแม่'],
        rolesEn: ['Ticket seller', 'Popcorn seller', 'Couple on a date', 'Film critic', 'Cleaner', 'Pirate filming the movie', 'Kid with parents'] },
      { name: 'คาสิโน', en: 'Casino', icon: '🎰', roles: ['เจ้ามือ', 'นักพนันขาประจำ', 'เศรษฐีมาเที่ยว', 'บอดี้การ์ด', 'บาร์เทนเดอร์', 'คนโกงไพ่', 'ผู้จัดการคาสิโน'],
        rolesEn: ['Dealer', 'Regular gambler', 'Rich tourist', 'Bodyguard', 'Bartender', 'Card cheat', 'Casino manager'] },
      { name: 'ฐานทัพทหาร', en: 'Military base', icon: '🪖', roles: ['นายพล', 'พลทหาร', 'หมอทหาร', 'คนครัว', 'ทหารยาม', 'นักบิน', 'ทหารเกณฑ์'],
        rolesEn: ['General', 'Private', 'Army medic', 'Cook', 'Sentry', 'Pilot', 'Conscript'] },
      { name: 'โรงพยาบาล', en: 'Hospital', icon: '🏥', roles: ['หมอศัลยกรรม', 'พยาบาล', 'คนไข้', 'ญาติคนไข้', 'เภสัชกร', 'พนักงานเข็นเปล', 'นักศึกษาแพทย์'],
        rolesEn: ['Surgeon', 'Nurse', 'Patient', 'Patient\'s relative', 'Pharmacist', 'Porter', 'Medical student'] },
      { name: 'โรงแรม', en: 'Hotel', icon: '🏨', roles: ['พนักงานต้อนรับ', 'แม่บ้าน', 'พนักงานยกกระเป๋า', 'แขกฮันนีมูน', 'ผู้จัดการโรงแรม', 'บาร์เทนเดอร์', 'นักธุรกิจ'],
        rolesEn: ['Receptionist', 'Housekeeper', 'Bellhop', 'Honeymoon guest', 'Hotel manager', 'Bartender', 'Businessperson'] },
      { name: 'เรือดำน้ำ', en: 'Submarine', icon: '🌊', roles: ['กัปตัน', 'ต้นหน', 'พนักงานโซนาร์', 'ช่างเครื่อง', 'คนครัว', 'ทหารเรือ', 'หมอประจำเรือ'],
        rolesEn: ['Captain', 'Navigator', 'Sonar operator', 'Engineer', 'Cook', 'Sailor', 'Ship doctor'] },
      { name: 'สถานีอวกาศ', en: 'Space station', icon: '🚀', roles: ['ผู้บัญชาการ', 'นักวิทยาศาสตร์', 'วิศวกร', 'นักบินอวกาศ', 'หมอ', 'นักท่องเที่ยวอวกาศ', 'มนุษย์ต่างดาว'],
        rolesEn: ['Commander', 'Scientist', 'Engineer', 'Astronaut', 'Doctor', 'Space tourist', 'Alien'] },
      { name: 'เรือโจรสลัด', en: 'Pirate ship', icon: '🏴‍☠️', roles: ['กัปตันโจรสลัด', 'ต้นเรือ', 'คนครัว', 'นักโทษ', 'พลปืนใหญ่', 'คนเฝ้าเสากระโดง', 'คนขุดสมบัติ'],
        rolesEn: ['Pirate captain', 'First mate', 'Cook', 'Prisoner', 'Gunner', 'Lookout', 'Treasure digger'] },
      { name: 'โรงเรียน', en: 'School', icon: '🏫', roles: ['ครูใหญ่', 'ครูประจำชั้น', 'นักเรียนหัวโจก', 'นักเรียนเรียนเก่ง', 'ภารโรง', 'แม่ค้าโรงอาหาร', 'ครูพละ'],
        rolesEn: ['Principal', 'Homeroom teacher', 'Class troublemaker', 'Top student', 'Janitor', 'Cafeteria vendor', 'PE teacher'] },
      { name: 'ซูเปอร์มาร์เก็ต', en: 'Supermarket', icon: '🛒', roles: ['แคชเชียร์', 'พนักงานจัดของ', 'คนแจกของชิม', 'แม่บ้านมาซื้อของ', 'ยาม', 'ผู้จัดการสาขา', 'เด็กหลงพ่อแม่'],
        rolesEn: ['Cashier', 'Shelf stocker', 'Free-sample giver', 'Shopper', 'Security guard', 'Store manager', 'Lost child'] },
      { name: 'ร้านอาหารหรู', en: 'Fancy restaurant', icon: '🍽️', roles: ['เชฟ', 'บริกร', 'นักวิจารณ์อาหาร', 'ลูกค้าวีไอพี', 'คนล้างจาน', 'ซอมเมอลิเย่ร์', 'นักดนตรี'],
        rolesEn: ['Chef', 'Waiter', 'Food critic', 'VIP guest', 'Dishwasher', 'Sommelier', 'Musician'] },
      { name: 'รถไฟ', en: 'Train', icon: '🚆', roles: ['คนขับรถไฟ', 'พนักงานตรวจตั๋ว', 'คนขายข้าวกล่อง', 'ผู้โดยสาร', 'นักท่องเที่ยวแบกเป้', 'ตำรวจรถไฟ', 'คนแอบขึ้นฟรี'],
        rolesEn: ['Train driver', 'Ticket inspector', 'Lunchbox seller', 'Passenger', 'Backpacker', 'Railway police', 'Fare dodger'] },
      { name: 'สถานีตำรวจ', en: 'Police station', icon: '🚓', roles: ['สารวัตร', 'ตำรวจจราจร', 'นักสืบ', 'ผู้ต้องหา', 'ทนายความ', 'นักข่าว', 'ผู้เสียหาย'],
        rolesEn: ['Inspector', 'Traffic officer', 'Detective', 'Suspect', 'Lawyer', 'Journalist', 'Victim'] },
      { name: 'ละครสัตว์', en: 'Circus', icon: '🎪', roles: ['ตัวตลก', 'นักกายกรรม', 'คนฝึกสัตว์', 'นักมายากล', 'ผู้ชม', 'คนขายตั๋ว', 'นักเดินไต่ลวด'],
        rolesEn: ['Clown', 'Acrobat', 'Animal trainer', 'Magician', 'Spectator', 'Ticket seller', 'Tightrope walker'] },
      { name: 'เรือสำราญ', en: 'Cruise ship', icon: '🛳️', roles: ['กัปตัน', 'นักร้องประจำเรือ', 'บาร์เทนเดอร์', 'ผู้โดยสารเกษียณ', 'คู่ฮันนีมูน', 'พนักงานทำความสะอาด', 'คนครัว'],
        rolesEn: ['Captain', 'Lounge singer', 'Bartender', 'Retired passenger', 'Honeymoon couple', 'Cleaner', 'Cook'] },
      { name: 'สถานทูต', en: 'Embassy', icon: '🏛️', roles: ['เอกอัครราชทูต', 'ยาม', 'เลขานุการ', 'คนมาขอวีซ่า', 'ล่าม', 'นักการทูต', 'นักข่าว'],
        rolesEn: ['Ambassador', 'Guard', 'Secretary', 'Visa applicant', 'Interpreter', 'Diplomat', 'Journalist'] },
      { name: 'มหาวิทยาลัย', en: 'University', icon: '🎓', roles: ['ศาสตราจารย์', 'นักศึกษาปีหนึ่ง', 'รุ่นพี่ว้าก', 'บรรณารักษ์', 'คณบดี', 'ยามหน้าประตู', 'นักศึกษาปริญญาเอก'],
        rolesEn: ['Professor', 'Freshman', 'Hazing senior', 'Librarian', 'Dean', 'Gate guard', 'PhD student'] },
    ],
  },
  thai: {
    name: 'สถานที่ในไทย', en: 'Places in Thailand', icon: '🇹🇭', desc: 'ที่ที่คนไทยไปกันบ่อย', descEn: 'Places Thais go all the time',
    list: [
      { name: 'ตลาดน้ำ', en: 'Floating market', icon: '🛶', roles: ['แม่ค้าขายก๋วยเตี๋ยวเรือ', 'นักท่องเที่ยวต่างชาติ', 'คนพายเรือ', 'แม่ค้าขายผลไม้', 'ช่างภาพ', 'ไกด์', 'เด็กขายพวงมาลัย'],
        rolesEn: ['Boat-noodle vendor', 'Foreign tourist', 'Boat rower', 'Fruit vendor', 'Photographer', 'Tour guide', 'Garland-selling kid'] },
      { name: 'วัด', en: 'Temple', icon: '🛕', roles: ['เจ้าอาวาส', 'พระลูกวัด', 'เด็กวัด', 'คนมาทำบุญ', 'แม่ชี', 'มัคนายก', 'หมอดู'],
        rolesEn: ['Abbot', 'Monk', 'Temple boy', 'Merit maker', 'Nun', 'Temple steward', 'Fortune teller'] },
      { name: 'ร้านสะดวกซื้อ', en: 'Convenience store', icon: '🏪', roles: ['พนักงานแคชเชียร์', 'คนมาซื้อมาม่าตอนดึก', 'คนส่งของ', 'นักเรียนซื้อขนม', 'คนมาจ่ายบิล', 'ผู้จัดการร้าน', 'ไรเดอร์'],
        rolesEn: ['Cashier', 'Late-night instant-noodle buyer', 'Delivery driver', 'Student buying snacks', 'Bill payer', 'Store manager', 'Food-delivery rider'] },
      { name: 'ร้านหมูกระทะ', en: 'Thai BBQ restaurant', icon: '🥓', roles: ['เจ้าของร้าน', 'เด็กเติมถ่าน', 'แก๊งเพื่อนมหาลัย', 'ครอบครัวมากินวันเกิด', 'คนล้างกระทะ', 'นักร้องโฟล์คซอง', 'คนเติมน้ำจิ้ม'],
        rolesEn: ['Owner', 'Charcoal kid', 'University friends', 'Family at a birthday', 'Pan washer', 'Folk singer', 'Sauce refiller'] },
      { name: 'รถไฟฟ้า', en: 'Skytrain', icon: '🚝', roles: ['พนักงานขายตั๋ว', 'คนทำงานออฟฟิศ', 'นักเรียน', 'รปภ.ประจำสถานี', 'คนแย่งที่นั่ง', 'นักท่องเที่ยวหลงทาง', 'คนดูมือถือทั้งทาง'],
        rolesEn: ['Ticket clerk', 'Office worker', 'Student', 'Station guard', 'Seat grabber', 'Lost tourist', 'Phone scroller'] },
      { name: 'งานวัด', en: 'Temple fair', icon: '🎡', roles: ['คนขายลูกชิ้นปิ้ง', 'คนคุมชิงช้าสวรรค์', 'เด็กเล่นปาเป้า', 'นักร้องลูกทุ่ง', 'คู่รักเดินเที่ยว', 'คนขายสายไหม', 'กรรมการวัด'],
        rolesEn: ['Meatball-skewer vendor', 'Ferris-wheel operator', 'Kid playing darts', 'Luk thung singer', 'Couple strolling', 'Cotton-candy seller', 'Fair committee member'] },
      { name: 'เวทีมวยไทย', en: 'Muay Thai stadium', icon: '🥊', roles: ['นักมวย', 'กรรมการบนเวที', 'เซียนมวย', 'คนเป่าปี่', 'ครูมวย', 'หมอประจำเวที', 'นักท่องเที่ยว'],
        rolesEn: ['Boxer', 'Referee', 'Betting expert', 'Pipe player', 'Trainer', 'Ringside doctor', 'Tourist'] },
      { name: 'งานแต่งงาน', en: 'Wedding', icon: '💒', roles: ['เจ้าบ่าว', 'เจ้าสาว', 'เพื่อนเจ้าบ่าว', 'แม่เจ้าสาว', 'พิธีกร', 'ช่างภาพ', 'แขกมากินฟรี'],
        rolesEn: ['Groom', 'Bride', 'Best man', 'Mother of the bride', 'MC', 'Photographer', 'Free-food guest'] },
      { name: 'ห้างสรรพสินค้า', en: 'Shopping mall', icon: '🛍️', roles: ['พนักงานขายเครื่องสำอาง', 'ยามหน้าห้าง', 'วัยรุ่นมาเดินเล่น', 'คนหาที่จอดรถ', 'พนักงานฟู้ดคอร์ท', 'คนมาตากแอร์', 'มาสคอตแจกใบปลิว'],
        rolesEn: ['Cosmetics salesperson', 'Mall guard', 'Teen hanging out', 'Driver looking for parking', 'Food-court worker', 'Person enjoying the AC', 'Mascot handing out flyers'] },
      { name: 'ร้านตัดผม', en: 'Barbershop', icon: '💈', roles: ['ช่างตัดผม', 'ลูกค้าตัดทรงนักเรียน', 'คนสระผม', 'ลูกค้าทำสีผม', 'คนรอคิวอ่านหนังสือพิมพ์', 'เจ้าของร้าน', 'เด็กฝึกงาน'],
        rolesEn: ['Barber', 'Student getting a school cut', 'Hair washer', 'Customer dyeing hair', 'Customer reading the paper', 'Owner', 'Trainee'] },
      { name: 'ฟิตเนส', en: 'Gym', icon: '🏋️', roles: ['เทรนเนอร์', 'คนมาเล่นวันแรก', 'นักกล้าม', 'คนมาถ่ายรูปลงโซเชียล', 'พนักงานขายคอร์ส', 'ครูสอนโยคะ', 'แม่บ้านทำความสะอาด'],
        rolesEn: ['Trainer', 'First-timer', 'Bodybuilder', 'Social-media poser', 'Membership salesperson', 'Yoga teacher', 'Cleaner'] },
      { name: 'ร้านกาแฟ', en: 'Coffee shop', icon: '☕', roles: ['บาริสต้า', 'ฟรีแลนซ์นั่งทำงาน', 'นักศึกษาอ่านหนังสือ', 'คนมาประชุม', 'คนรีวิวร้าน', 'เจ้าของร้าน', 'คนมาเดตแรก'],
        rolesEn: ['Barista', 'Freelancer', 'Student studying', 'Meeting attendee', 'Café reviewer', 'Owner', 'First date'] },
      { name: 'คอนเสิร์ต', en: 'Concert', icon: '🎤', roles: ['นักร้องนำ', 'มือกลอง', 'แฟนคลับแถวหน้า', 'ซาวด์เอนจิเนียร์', 'การ์ดหน้าเวที', 'คนขายเสื้อวง', 'คนอัดคลิปทั้งงาน'],
        rolesEn: ['Lead singer', 'Drummer', 'Front-row fan', 'Sound engineer', 'Stage guard', 'Merch seller', 'Person filming everything'] },
      { name: 'สถานีขนส่ง', en: 'Bus terminal', icon: '🚌', roles: ['คนขับรถทัวร์', 'พนักงานขายตั๋ว', 'คนกลับบ้านต่างจังหวัด', 'แม่ค้าขายข้าวเหนียวหมูปิ้ง', 'วินมอเตอร์ไซค์', 'คนนอนรอรถ', 'นายท่า'],
        rolesEn: ['Coach driver', 'Ticket seller', 'Person heading home upcountry', 'Sticky-rice-and-pork vendor', 'Motorbike taxi', 'Person sleeping while waiting', 'Station master'] },
      { name: 'ร้านนวดแผนไทย', en: 'Thai massage shop', icon: '💆', roles: ['หมอนวด', 'ลูกค้าปวดหลัง', 'นักท่องเที่ยวต่างชาติ', 'เจ้าของร้าน', 'คนนวดเท้า', 'ลูกค้าประจำ', 'พนักงานต้อนรับ'],
        rolesEn: ['Masseuse', 'Customer with back pain', 'Foreign tourist', 'Owner', 'Foot masseuse', 'Regular customer', 'Receptionist'] },
    ],
  },
};

// เวลาต่อรอบ (นาที)
const TIME_OPTIONS = [5, 6, 7, 8, 10, 12, 15];
