'use strict';
// ข้อมูลบทบาททั้งหมด (อ้างอิงรายชื่อและแต้มบทบาทจาก Ultimate Werewolf ฉบับภาษาไทย)
// team: village = ฝ่ายชาวบ้าน, wolf = ฝ่ายมนุษย์หมาป่า, solo = เล่นคนเดียว
// max: จำนวนสูงสุดในเกม, min: ถ้าใส่ต้องมีอย่างน้อยเท่านี้
// wake: บทพากย์ตอนเรียกให้ลืมตา (ใช้อัดเสียงด้วย)

const ROLES = {
  // ---------- ฝ่ายชาวบ้าน ----------
  villager: { name: 'ชาวบ้าน', en: 'Villager', icon: '🧑‍🌾', team: 'village', points: 1, max: 99,
    desc: 'ไม่มีพลังพิเศษ ใช้การสังเกตและการโหวตเพื่อไล่ล่ามนุษย์หมาป่า',
    descEn: 'No special powers. Use observation and your vote to hunt the werewolves.' },
  seer: { name: 'เทพพยากรณ์', en: 'Seer', icon: '🔮', team: 'village', points: 7,
    desc: 'ทุกคืน เลือกตรวจสอบผู้เล่น 1 คนว่าเป็นมนุษย์หมาป่าหรือไม่',
    descEn: 'Each night, check one player to see if they are a werewolf.',
    wake: ['เทพพยากรณ์ ลืมตาขึ้น', 'เลือกผู้เล่นหนึ่งคนที่ต้องการตรวจสอบ'] },
  apprentice: { name: 'ศิษย์เทพพยากรณ์', en: 'Apprentice Seer', icon: '📖', team: 'village', points: 4,
    desc: 'ถ้าเทพพยากรณ์ตาย คุณจะสืบทอดพลัง — ตื่นขึ้นมาแทนทุกครั้งที่ได้ยินเรียกเทพพยากรณ์',
    descEn: 'If the Seer dies, you inherit the power — wake up whenever the Seer is called.' },
  aura: { name: 'ญาณทิพย์', en: 'Aura Seer', icon: '✨', team: 'village', points: 3,
    desc: 'ทุกคืน ตรวจสอบผู้เล่น 1 คนว่ามีบทบาทพิเศษหรือไม่ (ไม่ใช่ชาวบ้านธรรมดาหรือมนุษย์หมาป่าธรรมดา)',
    descEn: 'Each night, check one player to see if they have a special role (not a plain Villager or Werewolf).',
    wake: ['ญาณทิพย์ ลืมตาขึ้น', 'เลือกผู้เล่นหนึ่งคน เพื่อดูว่ามีพลังพิเศษหรือไม่'] },
  mystic: { name: 'เทพผู้รู้แจ้ง', en: 'Mystic Seer', icon: '👁️', team: 'village', points: 9,
    desc: 'ทุกคืน เลือกผู้เล่น 1 คนเพื่อดูบทบาทที่แท้จริง',
    descEn: 'Each night, choose one player to see their true role.',
    wake: ['เทพผู้รู้แจ้ง ลืมตาขึ้น', 'เลือกผู้เล่นหนึ่งคน เพื่อดูบทบาทที่แท้จริง'] },
  mentalist: { name: 'นักสะกดจิต', en: 'Mentalist', icon: '🌀', team: 'village', points: 6,
    desc: 'ทุกคืน เลือกผู้เล่น 2 คนเพื่อตรวจว่าอยู่ฝ่ายเดียวกันหรือไม่',
    descEn: 'Each night, choose two players to see if they are on the same team.',
    wake: ['นักสะกดจิต ลืมตาขึ้น', 'เลือกผู้เล่นสองคน เพื่อดูว่าอยู่ฝ่ายเดียวกันหรือไม่'] },
  pi: { name: 'นักสืบเรื่องลี้ลับ', en: 'P.I.', icon: '🕵️', team: 'village', points: 3,
    desc: 'ครั้งเดียวต่อเกม ชี้ผู้เล่น 1 คน เพื่อตรวจว่าเขาและคนที่นั่งข้างซ้ายขวามีมนุษย์หมาป่าหรือไม่',
    descEn: 'Once per game, point at one player to check if they or their left/right neighbours include a werewolf.',
    wake: ['นักสืบเรื่องลี้ลับ ลืมตาขึ้น', 'จะใช้พลังสืบสวนคืนนี้หรือไม่'] },
  bodyguard: { name: 'บอดี้การ์ด', en: 'Bodyguard', icon: '🛡️', team: 'village', points: 3,
    desc: 'ทุกคืน เลือกปกป้องผู้เล่น 1 คนไม่ให้ถูกกำจัดในคืนนั้น (เลือกตัวเองได้ แต่ห้ามเลือกคนเดิมสองคืนติด)',
    descEn: 'Each night, protect one player from being eliminated (yourself included, but not the same player two nights in a row).',
    wake: ['บอดี้การ์ด ลืมตาขึ้น', 'เลือกผู้เล่นหนึ่งคนที่จะปกป้องในคืนนี้'] },
  priest: { name: 'นักบวช', en: 'Priest', icon: '🙏', team: 'village', points: 3,
    desc: 'ครั้งเดียวต่อเกม อวยพรผู้เล่น 1 คน ให้รอดพ้นจากการถูกกำจัดได้หนึ่งครั้ง',
    descEn: 'Once per game, bless one player so they survive being eliminated once.',
    wake: ['นักบวช ลืมตาขึ้น', 'จะอวยพรใครหรือไม่'] },
  witch: { name: 'แม่มด', en: 'Witch', icon: '🧙‍♀️', team: 'village', points: 4,
    desc: 'มียาชุบชีวิต 1 ขวด และยาพิษ 1 ขวดต่อเกม ใช้ช่วยคนที่ถูกหมาป่าเลือก หรือกำจัดใครก็ได้ในตอนกลางคืน',
    descEn: 'You have one healing potion and one poison per game: save the wolves\' victim, or kill anyone at night.',
    wake: ['แม่มด ลืมตาขึ้น', 'ดูว่าคืนนี้ใครถูกทำร้าย แล้วตัดสินใจว่าจะใช้ยาหรือไม่'] },
  hunter: { name: 'นายพราน', en: 'Hunter', icon: '🏹', team: 'village', points: 3,
    desc: 'ถ้าคุณถูกกำจัด ไม่ว่าด้วยเหตุใด สามารถยิงพาผู้เล่นอีก 1 คนไปด้วยได้ทันที',
    descEn: 'If you are eliminated for any reason, you may immediately shoot one other player.' },
  huntress: { name: 'พรานหญิง', en: 'Huntress', icon: '🎯', team: 'village', points: 3,
    desc: 'ครั้งเดียวต่อเกม สามารถกำจัดผู้เล่น 1 คนในตอนกลางคืน',
    descEn: 'Once per game, eliminate one player at night.',
    wake: ['พรานหญิง ลืมตาขึ้น', 'จะล่าใครในคืนนี้หรือไม่'] },
  revealer: { name: 'ผู้เผยตัวตน', en: 'Revealer', icon: '🔦', team: 'village', points: 4,
    desc: 'ทุกคืน ชี้ผู้เล่นได้ 1 คน ถ้าเป็นมนุษย์หมาป่า เขาจะถูกกำจัด แต่ถ้าไม่ใช่ คุณจะถูกกำจัดแทน (เลือกไม่ชี้ก็ได้)',
    descEn: 'Each night you may point at one player. If they are a werewolf they die — if not, you die instead (you may skip).',
    wake: ['ผู้เผยตัวตน ลืมตาขึ้น', 'จะชี้ตัวใครหรือไม่ ถ้าชี้ผิด คุณจะตายเอง'] },
  cupid: { name: 'กามเทพ', en: 'Cupid', icon: '💘', team: 'village', points: -3,
    desc: 'คืนแรก เลือกผู้เล่น 2 คนให้เป็นคู่รัก ถ้าคนหนึ่งตาย อีกคนจะตรอมใจตายตาม',
    descEn: 'On the first night, choose two players to be lovers. If one dies, the other dies of heartbreak.',
    wake: ['กามเทพ ลืมตาขึ้น', 'เลือกผู้เล่นสองคนให้เป็นคู่รักกัน'] },
  mason: { name: 'ภราดรแห่งเมสัน', en: 'Mason', icon: '🧱', team: 'village', points: 2, min: 2, max: 4,
    desc: 'คืนแรก ลืมตาขึ้นมาดูว่าใครเป็นภราดรด้วยกัน (ต้องมีอย่างน้อย 2 คน)',
    descEn: 'On the first night, wake up to see who the other Masons are (at least 2 needed).',
    wake: ['ภราดรแห่งเมสัน ลืมตาขึ้น', 'มองหน้ากันให้จำว่าใครเป็นพี่น้องภราดร'] },
  prince: { name: 'เจ้าชาย', en: 'Prince', icon: '🤴', team: 'village', points: 3,
    desc: 'ถ้าถูกโหวตประหาร ให้เผยตัวว่าเป็นเจ้าชายและรอดไปได้ 1 ครั้ง (แต่ถ้าถูกหมาป่าฆ่าก็ตายตามปกติ)',
    descEn: 'If voted out, reveal yourself as the Prince and survive once (but you still die to werewolves).' },
  mayor: { name: 'นายกเทศมนตรี', en: 'Mayor', icon: '🎩', team: 'village', points: 2,
    desc: 'ตอนโหวต เสียงของคุณนับเป็น 2 เสียง',
    descEn: 'Your vote counts twice.' },
  toughguy: { name: 'หนุ่มถึก', en: 'Tough Guy', icon: '💪', team: 'village', points: 3,
    desc: 'ถ้าถูกหมาป่ากัด คุณจะยังไม่ตายทันที แต่จะตายในคืนถัดไป',
    descEn: 'If bitten by werewolves, you don\'t die right away — you die the following night.' },
  diseased: { name: 'ผู้ป่วยติดเชื้อ', en: 'Diseased', icon: '🤒', team: 'village', points: 3,
    desc: 'ถ้าคุณถูกหมาป่าฆ่า หมาป่าจะป่วยและล่าใครไม่ได้ในคืนถัดไป',
    descEn: 'If the werewolves kill you, they get sick and can\'t hunt the next night.' },
  lycan: { name: 'ลูกครึ่งมนุษย์หมาป่า', en: 'Lycan', icon: '🌗', team: 'village', points: -1,
    desc: 'คุณอยู่ฝ่ายชาวบ้าน แต่เทพพยากรณ์จะมองเห็นคุณเป็นมนุษย์หมาป่า',
    descEn: 'You are on the villagers\' team, but the Seer sees you as a werewolf.' },
  oldhag: { name: 'แม่หมอ', en: 'Old Hag', icon: '🧿', team: 'village', points: 1,
    desc: 'ทุกคืน สาปผู้เล่น 1 คนให้ออกจากหมู่บ้านในวันถัดไป (ห้ามพูด ห้ามโหวต และไม่ถูกโหวต)',
    descEn: 'Each night, curse one player to leave the village the next day (no talking, no voting, can\'t be voted).',
    wake: ['แม่หมอ ลืมตาขึ้น', 'เลือกผู้เล่นหนึ่งคน ที่จะสาปให้ออกจากหมู่บ้านในวันพรุ่งนี้'] },
  spellcaster: { name: 'จอมเวท', en: 'Spellcaster', icon: '🪄', team: 'village', points: 1,
    desc: 'ทุกคืน เลือกผู้เล่น 1 คนให้ห้ามพูดในวันถัดไป',
    descEn: 'Each night, choose one player who may not speak the next day.',
    wake: ['จอมเวท ลืมตาขึ้น', 'เลือกผู้เล่นหนึ่งคน ที่จะห้ามพูดในวันพรุ่งนี้'] },
  troublemaker: { name: 'ตัวป่วน', en: 'Troublemaker', icon: '😈', team: 'village', points: -3,
    desc: 'ครั้งเดียวต่อเกม ป่วนหมู่บ้านให้วันรุ่งขึ้นมีการโหวตประหาร 2 รอบ',
    descEn: 'Once per game, stir up trouble so the next day has two executions.',
    wake: ['ตัวป่วน ลืมตาขึ้น', 'จะป่วนให้พรุ่งนี้มีการประหารสองครั้งหรือไม่'] },
  pacifist: { name: 'ผู้รักสันติ', en: 'Pacifist', icon: '🕊️', team: 'village', points: -1,
    desc: 'คุณต้องโหวตให้ผู้ถูกกล่าวหารอดเสมอ',
    descEn: 'You must always vote to spare the accused.' },
  idiot: { name: 'ไอ้ทึ่ม', en: 'Village Idiot', icon: '🤪', team: 'village', points: 2,
    desc: 'คุณต้องโหวตให้ประหารเสมอ',
    descEn: 'You must always vote to execute.' },
  bomber: { name: 'มือระเบิดพลีชีพ', en: 'Mad Bomber', icon: '💣', team: 'village', points: -2,
    desc: 'ถ้าคุณถูกกำจัด ผู้เล่นที่นั่งติดกับคุณทั้งซ้ายและขวาจะตายไปด้วย',
    descEn: 'If you are eliminated, the players sitting on both sides of you die too.' },
  cursed: { name: 'ผู้ต้องคำสาป', en: 'Cursed', icon: '🩸', team: 'village', points: -3,
    desc: 'เริ่มเกมเป็นฝ่ายชาวบ้าน แต่ถ้าหมาป่ากัดคุณ คุณจะไม่ตายและกลายเป็นมนุษย์หมาป่าแทน',
    descEn: 'You start as a villager, but if the werewolves bite you, you don\'t die — you become a werewolf.',
    wake: ['ผู้ต้องคำสาป ลืมตาขึ้น', 'ดูหน้าจอว่าคืนนี้คุณยังเป็นมนุษย์อยู่หรือไม่'] },

  // ---------- ฝ่ายมนุษย์หมาป่า ----------
  werewolf: { name: 'มนุษย์หมาป่า', en: 'Werewolf', icon: '🐺', team: 'wolf', points: -6, max: 8,
    desc: 'ทุกคืน ตื่นขึ้นมาพร้อมหมาป่าตัวอื่นและเลือกกำจัดผู้เล่น 1 คน ชนะเมื่อหมาป่ามีจำนวนเท่ากับฝ่ายอื่น',
    descEn: 'Each night, wake with the other werewolves and eliminate one player. Win when werewolves equal everyone else.' },
  wolfcub: { name: 'ลูกมนุษย์หมาป่า', en: 'Wolf Cub', icon: '🐶', team: 'wolf', points: -8,
    desc: 'ตื่นพร้อมหมาป่าทุกคืน ถ้าคุณถูกกำจัด ฝูงหมาป่าจะได้ฆ่า 2 คนในคืนถัดไป',
    descEn: 'Wake with the werewolves each night. If you are eliminated, the pack kills two the next night.' },
  minion: { name: 'สมุนรับใช้', en: 'Minion', icon: '🦹', team: 'wolf', points: -6,
    desc: 'คุณรู้ว่าใครเป็นหมาป่า (ลืมตาเฉพาะคืนแรก) แต่หมาป่าไม่รู้ว่าคุณคือใคร คุณชนะเมื่อหมาป่าชนะ',
    descEn: 'You know who the werewolves are (first night only), but they don\'t know you. You win when the werewolves win.',
    wake: ['สมุนรับใช้ ลืมตาขึ้น', 'ดูหน้าจอให้จำว่าใครคือมนุษย์หมาป่า'] },
  sorcerer: { name: 'นางปีศาจ', en: 'Sorcerer', icon: '🧛‍♀️', team: 'wolf', points: -3,
    desc: 'ทุกคืน ตรวจสอบผู้เล่น 1 คนว่าเป็นเทพพยากรณ์หรือไม่ คุณอยู่ฝ่ายหมาป่า (แต่เทพพยากรณ์เห็นคุณเป็นคนธรรมดา)',
    descEn: 'Each night, check one player to see if they are the Seer. You are on the wolves\' team (the Seer sees you as normal).',
    wake: ['นางปีศาจ ลืมตาขึ้น', 'เลือกผู้เล่นหนึ่งคน เพื่อดูว่าเป็นเทพพยากรณ์หรือไม่'] },

  // ---------- เล่นคนเดียว ----------
  tanner: { name: 'ยาจก', en: 'Tanner', icon: '🥀', team: 'solo', points: -2,
    desc: 'คุณหมดอาลัยตายอยาก จะชนะทันทีถ้าถูกหมู่บ้านโหวตประหาร',
    descEn: 'You are sick of life — you win immediately if the village votes you out.' },
};

const TEAMS = {
  village: { name: 'ฝ่ายชาวบ้าน', en: 'Village', icon: '🏡' },
  wolf: { name: 'ฝ่ายมนุษย์หมาป่า', en: 'Werewolves', icon: '🐺' },
  solo: { name: 'เล่นคนเดียว', en: 'Solo', icon: '🎭' },
};

// บทพากย์เรียกหมาป่า (หมาป่าและลูกหมาป่าตื่นพร้อมกัน)
const WOLF_WAKE = {
  first: ['มนุษย์หมาป่า ลืมตาขึ้น', 'มองหน้ากันให้จำว่าใครเป็นพวกเดียวกัน'],
  firstKill: ['มนุษย์หมาป่า ลืมตาขึ้น', 'มองหน้ากันให้จำว่าใครเป็นพวกเดียวกัน', 'แล้วเลือกเหยื่อที่จะกำจัดในคืนนี้'],
  normal: ['มนุษย์หมาป่า ลืมตาขึ้น', 'เลือกเหยื่อที่จะกำจัดในคืนนี้'],
  double: ['มนุษย์หมาป่า ลืมตาขึ้น', 'ฝูงหมาป่าโกรธแค้นที่ลูกหมาป่าตาย', 'คืนนี้เลือกเหยื่อได้สองคน'],
  sick: ['มนุษย์หมาป่า ลืมตาขึ้น', 'เมื่อคืนพวกคุณกินผู้ป่วยติดเชื้อเข้าไป', 'คืนนี้ป่วยหนัก ล่าใครไม่ได้'],
};

// ชุดบทบาทแนะนำ
const PRESETS = [
  { name: 'มือใหม่', en: 'Beginner', desc: 'ตามบทความ: เทพพยากรณ์ + บอดี้การ์ด', descEn: 'Seer + Bodyguard', roles: { seer: 1, bodyguard: 1 } },
  { name: 'คลาสสิก', en: 'Classic', desc: 'เทพพยากรณ์ แม่มด นายพราน', descEn: 'Seer, Witch, Hunter', roles: { seer: 1, witch: 1, hunter: 1 } },
  { name: 'วุ่นวาย', en: 'Chaos', desc: 'มีคู่รัก ลูกหมาป่า ยาจก และอีกมาก', descEn: 'Lovers, Wolf Cub, Tanner and more',
    roles: { seer: 1, bodyguard: 1, cupid: 1, hunter: 1, wolfcub: 1, minion: 1, tanner: 1, prince: 1, cursed: 1 } },
];
